### PR TITLE
fix: Avoid re-adding existing columns whose names require quoting

### PR DESCRIPTION
**Pull request by spencerjbeckwith**
This should fix a regression from #518. I got multiple failures on my overnight pipelines looking like this:

```
2026-09-01T08:00:06.148148Z [info     ] target-snowflake sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 001430 (42601): SQL compilation error:
2026-09-01T08:00:06.148213Z [info     ] target-snowflake column 'AMAZON-ORDER-ID' already exists
2026-09-01T08:00:06.148300Z [info     ] target-snowflake [SQL: ALTER TABLE "RAW"."AMAZON_SP"."AMAZONSP_FULFILLED_SHIPMENTS_REPORT" ADD COLUMN "amazon-order-id" VARCHAR]
```

My fault being pinned to main. This error happened for several taps for columns with hyphens, colons, and spaces.

Snowflake stores every identifier upper-case, and SQLAlchemy's `normalize_name` only lower-cases it back when the lower-case form doesn't need quoting. Names that do need quoting because of special characters or reserved words come back upper-case. `format_identifier` lower-cased them anyway, so `column_exists` never matched and `ALTER TABLE` fired for columns that already exist.

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
Thanks @spencerjbeckwith !
